# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

target 'ThunderCats Example' do
    pod 'ThunderCats', :path => '..'
end

target 'ThunderCats ExampleTests' do

end

